name: Frontend CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'rb-app/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'rb-app/**'

jobs:
  flutter-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rb-app

    steps:
    - uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true

    - run: flutter pub get
    - run: flutter analyze
    - run: flutter test